extends:
  - stylelint-config-standard
  - stylelint-config-styled-components

plugins:
  - stylelint-order

processors:
  - stylelint-processor-styled-components

syntax: scss

rules:
  # Order
  order/order: [
    custom-properties,
    declarations,
    rules
  ]
  order/properties-alphabetical-order: true
