// flow-typed signature: 90f220c70b3c10cf67d22e7f359588a8
// flow-typed version: <<STUB>>/dependency-comparator_v2.0.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dependency-comparator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'dependency-comparator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dependency-comparator/bin/brady-tool' {
  declare module.exports: any;
}

declare module 'dependency-comparator/gulpfile' {
  declare module.exports: any;
}

declare module 'dependency-comparator/html/htmlTableCreator' {
  declare module.exports: any;
}

declare module 'dependency-comparator/html/scripts/CheckBox' {
  declare module.exports: any;
}

declare module 'dependency-comparator/html/scripts/versioning' {
  declare module.exports: any;
}

declare module 'dependency-comparator/html/scripts/VersionPlugin' {
  declare module.exports: any;
}

declare module 'dependency-comparator/modules/colors' {
  declare module.exports: any;
}

declare module 'dependency-comparator/modules/logger' {
  declare module.exports: any;
}

declare module 'dependency-comparator/modules/parse' {
  declare module.exports: any;
}

declare module 'dependency-comparator/modules/server' {
  declare module.exports: any;
}

declare module 'dependency-comparator/modules/summary' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dependency-comparator/bin/brady-tool.js' {
  declare module.exports: $Exports<'dependency-comparator/bin/brady-tool'>;
}
declare module 'dependency-comparator/gulpfile.js' {
  declare module.exports: $Exports<'dependency-comparator/gulpfile'>;
}
declare module 'dependency-comparator/html/htmlTableCreator.js' {
  declare module.exports: $Exports<'dependency-comparator/html/htmlTableCreator'>;
}
declare module 'dependency-comparator/html/scripts/CheckBox.js' {
  declare module.exports: $Exports<'dependency-comparator/html/scripts/CheckBox'>;
}
declare module 'dependency-comparator/html/scripts/versioning.js' {
  declare module.exports: $Exports<'dependency-comparator/html/scripts/versioning'>;
}
declare module 'dependency-comparator/html/scripts/VersionPlugin.js' {
  declare module.exports: $Exports<'dependency-comparator/html/scripts/VersionPlugin'>;
}
declare module 'dependency-comparator/modules/colors.js' {
  declare module.exports: $Exports<'dependency-comparator/modules/colors'>;
}
declare module 'dependency-comparator/modules/logger.js' {
  declare module.exports: $Exports<'dependency-comparator/modules/logger'>;
}
declare module 'dependency-comparator/modules/parse.js' {
  declare module.exports: $Exports<'dependency-comparator/modules/parse'>;
}
declare module 'dependency-comparator/modules/server.js' {
  declare module.exports: $Exports<'dependency-comparator/modules/server'>;
}
declare module 'dependency-comparator/modules/summary.js' {
  declare module.exports: $Exports<'dependency-comparator/modules/summary'>;
}
