// flow-typed signature: 59d5fd5aa2b38bd0137b7ec96142955e
// flow-typed version: <<STUB>>/pixi.js_v4.3.4/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pixi.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pixi.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pixi.js/dist/pixi' {
  declare module.exports: any;
}

declare module 'pixi.js/dist/pixi.min' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/accessibility/AccessibilityManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/accessibility/accessibleTarget' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/accessibility/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/Application' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/autoDetectRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/const' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/Bounds' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/Container' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/DisplayObject' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/Transform' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/TransformBase' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/display/TransformStatic' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/canvas/CanvasGraphicsRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/Graphics' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/GraphicsData' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/utils/bezierCurveTo' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/GraphicsRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/shaders/PrimitiveShader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildCircle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildComplexPoly' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildLine' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildPoly' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildRectangle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/utils/buildRoundedRectangle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/graphics/webgl/WebGLGraphicsData' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/GroupD8' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/Matrix' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/ObservablePoint' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/Point' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/shapes/Circle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/shapes/Ellipse' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/shapes/Polygon' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/shapes/Rectangle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/math/shapes/RoundedRectangle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/canvas/CanvasRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/canvas/utils/canUseNewCanvasBlendModes' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/canvas/utils/CanvasMaskManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/canvas/utils/CanvasRenderTarget' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/canvas/utils/mapCanvasBlendModesToPixi' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/SystemRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/filters/extractUniformsFromSrc' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/filters/Filter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/filters/filterTransforms' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/managers/BlendModeManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/managers/FilterManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/managers/MaskManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/managers/StencilManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/managers/WebGLManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/TextureGarbageCollector' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/TextureManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/checkMaxIfStatmentsInShader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/mapWebGLBlendModesToPixi' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/mapWebGLDrawModesToPixi' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/ObjectRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/Quad' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/RenderTarget' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/utils/validateContext' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/WebGLRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/renderers/webgl/WebGLState' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/settings' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/Shader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/canvas/CanvasSpriteRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/canvas/CanvasTinter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/Sprite' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/webgl/BatchBuffer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/webgl/generateMultiTextureShader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/sprites/webgl/SpriteRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/text/Text' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/text/TextStyle' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/BaseRenderTexture' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/BaseTexture' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/RenderTexture' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/Texture' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/TextureUvs' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/textures/VideoBaseTexture' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/ticker/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/ticker/Ticker' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/canUploadSameBuffer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/createIndicesForQuads' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/determineCrossOrigin' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/maxRecommendedTextures' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/core/utils/pluginTarget' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/deprecation' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extract/canvas/CanvasExtract' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extract/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extract/webgl/WebGLExtract' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/AnimatedSprite' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/BitmapText' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/cacheAsBitmap' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/getChildByName' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/getGlobalPosition' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/TextureTransform' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/TilingSprite' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/extras/webgl/TilingSpriteRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/BlurFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/BlurXFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/BlurYFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/generateBlurFragSource' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/generateBlurVertSource' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/blur/getMaxBlurKernelSize' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/colormatrix/ColorMatrixFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/displacement/DisplacementFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/fxaa/FXAAFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/noise/NoiseFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/filters/void/VoidFilter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/interaction/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/interaction/InteractionData' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/interaction/InteractionEvent' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/interaction/InteractionManager' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/interaction/interactiveTarget' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/loaders/bitmapFontParser' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/loaders/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/loaders/loader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/loaders/spritesheetParser' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/loaders/textureParser' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/canvas/CanvasMeshRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/Mesh' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/NineSlicePlane' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/Plane' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/Rope' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/mesh/webgl/MeshRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/particles/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/particles/ParticleContainer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/particles/webgl/ParticleBuffer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/particles/webgl/ParticleRenderer' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/particles/webgl/ParticleShader' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/polyfill/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/polyfill/Math.sign' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/polyfill/Object.assign' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/polyfill/requestAnimationFrame' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/BasePrepare' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/canvas/CanvasPrepare' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/index' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/limiters/CountLimiter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/limiters/TimeLimiter' {
  declare module.exports: any;
}

declare module 'pixi.js/lib/prepare/webgl/WebGLPrepare' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pixi.js/dist/pixi.js' {
  declare module.exports: $Exports<'pixi.js/dist/pixi'>;
}
declare module 'pixi.js/dist/pixi.min.js' {
  declare module.exports: $Exports<'pixi.js/dist/pixi.min'>;
}
declare module 'pixi.js/lib/accessibility/AccessibilityManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/accessibility/AccessibilityManager'>;
}
declare module 'pixi.js/lib/accessibility/accessibleTarget.js' {
  declare module.exports: $Exports<'pixi.js/lib/accessibility/accessibleTarget'>;
}
declare module 'pixi.js/lib/accessibility/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/accessibility/index'>;
}
declare module 'pixi.js/lib/core/Application.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/Application'>;
}
declare module 'pixi.js/lib/core/autoDetectRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/autoDetectRenderer'>;
}
declare module 'pixi.js/lib/core/const.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/const'>;
}
declare module 'pixi.js/lib/core/display/Bounds.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/Bounds'>;
}
declare module 'pixi.js/lib/core/display/Container.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/Container'>;
}
declare module 'pixi.js/lib/core/display/DisplayObject.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/DisplayObject'>;
}
declare module 'pixi.js/lib/core/display/Transform.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/Transform'>;
}
declare module 'pixi.js/lib/core/display/TransformBase.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/TransformBase'>;
}
declare module 'pixi.js/lib/core/display/TransformStatic.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/display/TransformStatic'>;
}
declare module 'pixi.js/lib/core/graphics/canvas/CanvasGraphicsRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/canvas/CanvasGraphicsRenderer'>;
}
declare module 'pixi.js/lib/core/graphics/Graphics.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/Graphics'>;
}
declare module 'pixi.js/lib/core/graphics/GraphicsData.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/GraphicsData'>;
}
declare module 'pixi.js/lib/core/graphics/utils/bezierCurveTo.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/utils/bezierCurveTo'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/GraphicsRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/GraphicsRenderer'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/shaders/PrimitiveShader.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/shaders/PrimitiveShader'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildCircle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildCircle'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildComplexPoly.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildComplexPoly'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildLine.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildLine'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildPoly.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildPoly'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildRectangle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildRectangle'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/utils/buildRoundedRectangle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/utils/buildRoundedRectangle'>;
}
declare module 'pixi.js/lib/core/graphics/webgl/WebGLGraphicsData.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/graphics/webgl/WebGLGraphicsData'>;
}
declare module 'pixi.js/lib/core/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/index'>;
}
declare module 'pixi.js/lib/core/math/GroupD8.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/GroupD8'>;
}
declare module 'pixi.js/lib/core/math/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/index'>;
}
declare module 'pixi.js/lib/core/math/Matrix.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/Matrix'>;
}
declare module 'pixi.js/lib/core/math/ObservablePoint.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/ObservablePoint'>;
}
declare module 'pixi.js/lib/core/math/Point.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/Point'>;
}
declare module 'pixi.js/lib/core/math/shapes/Circle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/shapes/Circle'>;
}
declare module 'pixi.js/lib/core/math/shapes/Ellipse.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/shapes/Ellipse'>;
}
declare module 'pixi.js/lib/core/math/shapes/Polygon.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/shapes/Polygon'>;
}
declare module 'pixi.js/lib/core/math/shapes/Rectangle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/shapes/Rectangle'>;
}
declare module 'pixi.js/lib/core/math/shapes/RoundedRectangle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/math/shapes/RoundedRectangle'>;
}
declare module 'pixi.js/lib/core/renderers/canvas/CanvasRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/canvas/CanvasRenderer'>;
}
declare module 'pixi.js/lib/core/renderers/canvas/utils/canUseNewCanvasBlendModes.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/canvas/utils/canUseNewCanvasBlendModes'>;
}
declare module 'pixi.js/lib/core/renderers/canvas/utils/CanvasMaskManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/canvas/utils/CanvasMaskManager'>;
}
declare module 'pixi.js/lib/core/renderers/canvas/utils/CanvasRenderTarget.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/canvas/utils/CanvasRenderTarget'>;
}
declare module 'pixi.js/lib/core/renderers/canvas/utils/mapCanvasBlendModesToPixi.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/canvas/utils/mapCanvasBlendModesToPixi'>;
}
declare module 'pixi.js/lib/core/renderers/SystemRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/SystemRenderer'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/filters/extractUniformsFromSrc.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/filters/extractUniformsFromSrc'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/filters/Filter.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/filters/Filter'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/filters/filterTransforms.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/filters/filterTransforms'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/filters/spriteMask/SpriteMaskFilter'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/managers/BlendModeManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/managers/BlendModeManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/managers/FilterManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/managers/FilterManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/managers/MaskManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/managers/MaskManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/managers/StencilManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/managers/StencilManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/managers/WebGLManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/managers/WebGLManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/TextureGarbageCollector.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/TextureGarbageCollector'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/TextureManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/TextureManager'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/checkMaxIfStatmentsInShader.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/checkMaxIfStatmentsInShader'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/mapWebGLBlendModesToPixi.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/mapWebGLBlendModesToPixi'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/mapWebGLDrawModesToPixi.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/mapWebGLDrawModesToPixi'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/ObjectRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/ObjectRenderer'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/Quad.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/Quad'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/RenderTarget.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/RenderTarget'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/utils/validateContext.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/utils/validateContext'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/WebGLRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/WebGLRenderer'>;
}
declare module 'pixi.js/lib/core/renderers/webgl/WebGLState.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/renderers/webgl/WebGLState'>;
}
declare module 'pixi.js/lib/core/settings.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/settings'>;
}
declare module 'pixi.js/lib/core/Shader.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/Shader'>;
}
declare module 'pixi.js/lib/core/sprites/canvas/CanvasSpriteRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/canvas/CanvasSpriteRenderer'>;
}
declare module 'pixi.js/lib/core/sprites/canvas/CanvasTinter.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/canvas/CanvasTinter'>;
}
declare module 'pixi.js/lib/core/sprites/Sprite.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/Sprite'>;
}
declare module 'pixi.js/lib/core/sprites/webgl/BatchBuffer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/webgl/BatchBuffer'>;
}
declare module 'pixi.js/lib/core/sprites/webgl/generateMultiTextureShader.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/webgl/generateMultiTextureShader'>;
}
declare module 'pixi.js/lib/core/sprites/webgl/SpriteRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/sprites/webgl/SpriteRenderer'>;
}
declare module 'pixi.js/lib/core/text/Text.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/text/Text'>;
}
declare module 'pixi.js/lib/core/text/TextStyle.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/text/TextStyle'>;
}
declare module 'pixi.js/lib/core/textures/BaseRenderTexture.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/BaseRenderTexture'>;
}
declare module 'pixi.js/lib/core/textures/BaseTexture.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/BaseTexture'>;
}
declare module 'pixi.js/lib/core/textures/RenderTexture.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/RenderTexture'>;
}
declare module 'pixi.js/lib/core/textures/Texture.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/Texture'>;
}
declare module 'pixi.js/lib/core/textures/TextureUvs.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/TextureUvs'>;
}
declare module 'pixi.js/lib/core/textures/VideoBaseTexture.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/textures/VideoBaseTexture'>;
}
declare module 'pixi.js/lib/core/ticker/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/ticker/index'>;
}
declare module 'pixi.js/lib/core/ticker/Ticker.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/ticker/Ticker'>;
}
declare module 'pixi.js/lib/core/utils/canUploadSameBuffer.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/canUploadSameBuffer'>;
}
declare module 'pixi.js/lib/core/utils/createIndicesForQuads.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/createIndicesForQuads'>;
}
declare module 'pixi.js/lib/core/utils/determineCrossOrigin.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/determineCrossOrigin'>;
}
declare module 'pixi.js/lib/core/utils/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/index'>;
}
declare module 'pixi.js/lib/core/utils/maxRecommendedTextures.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/maxRecommendedTextures'>;
}
declare module 'pixi.js/lib/core/utils/pluginTarget.js' {
  declare module.exports: $Exports<'pixi.js/lib/core/utils/pluginTarget'>;
}
declare module 'pixi.js/lib/deprecation.js' {
  declare module.exports: $Exports<'pixi.js/lib/deprecation'>;
}
declare module 'pixi.js/lib/extract/canvas/CanvasExtract.js' {
  declare module.exports: $Exports<'pixi.js/lib/extract/canvas/CanvasExtract'>;
}
declare module 'pixi.js/lib/extract/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/extract/index'>;
}
declare module 'pixi.js/lib/extract/webgl/WebGLExtract.js' {
  declare module.exports: $Exports<'pixi.js/lib/extract/webgl/WebGLExtract'>;
}
declare module 'pixi.js/lib/extras/AnimatedSprite.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/AnimatedSprite'>;
}
declare module 'pixi.js/lib/extras/BitmapText.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/BitmapText'>;
}
declare module 'pixi.js/lib/extras/cacheAsBitmap.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/cacheAsBitmap'>;
}
declare module 'pixi.js/lib/extras/getChildByName.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/getChildByName'>;
}
declare module 'pixi.js/lib/extras/getGlobalPosition.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/getGlobalPosition'>;
}
declare module 'pixi.js/lib/extras/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/index'>;
}
declare module 'pixi.js/lib/extras/TextureTransform.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/TextureTransform'>;
}
declare module 'pixi.js/lib/extras/TilingSprite.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/TilingSprite'>;
}
declare module 'pixi.js/lib/extras/webgl/TilingSpriteRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/extras/webgl/TilingSpriteRenderer'>;
}
declare module 'pixi.js/lib/filters/blur/BlurFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/BlurFilter'>;
}
declare module 'pixi.js/lib/filters/blur/BlurXFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/BlurXFilter'>;
}
declare module 'pixi.js/lib/filters/blur/BlurYFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/BlurYFilter'>;
}
declare module 'pixi.js/lib/filters/blur/generateBlurFragSource.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/generateBlurFragSource'>;
}
declare module 'pixi.js/lib/filters/blur/generateBlurVertSource.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/generateBlurVertSource'>;
}
declare module 'pixi.js/lib/filters/blur/getMaxBlurKernelSize.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/blur/getMaxBlurKernelSize'>;
}
declare module 'pixi.js/lib/filters/colormatrix/ColorMatrixFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/colormatrix/ColorMatrixFilter'>;
}
declare module 'pixi.js/lib/filters/displacement/DisplacementFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/displacement/DisplacementFilter'>;
}
declare module 'pixi.js/lib/filters/fxaa/FXAAFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/fxaa/FXAAFilter'>;
}
declare module 'pixi.js/lib/filters/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/index'>;
}
declare module 'pixi.js/lib/filters/noise/NoiseFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/noise/NoiseFilter'>;
}
declare module 'pixi.js/lib/filters/void/VoidFilter.js' {
  declare module.exports: $Exports<'pixi.js/lib/filters/void/VoidFilter'>;
}
declare module 'pixi.js/lib/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/index'>;
}
declare module 'pixi.js/lib/interaction/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/interaction/index'>;
}
declare module 'pixi.js/lib/interaction/InteractionData.js' {
  declare module.exports: $Exports<'pixi.js/lib/interaction/InteractionData'>;
}
declare module 'pixi.js/lib/interaction/InteractionEvent.js' {
  declare module.exports: $Exports<'pixi.js/lib/interaction/InteractionEvent'>;
}
declare module 'pixi.js/lib/interaction/InteractionManager.js' {
  declare module.exports: $Exports<'pixi.js/lib/interaction/InteractionManager'>;
}
declare module 'pixi.js/lib/interaction/interactiveTarget.js' {
  declare module.exports: $Exports<'pixi.js/lib/interaction/interactiveTarget'>;
}
declare module 'pixi.js/lib/loaders/bitmapFontParser.js' {
  declare module.exports: $Exports<'pixi.js/lib/loaders/bitmapFontParser'>;
}
declare module 'pixi.js/lib/loaders/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/loaders/index'>;
}
declare module 'pixi.js/lib/loaders/loader.js' {
  declare module.exports: $Exports<'pixi.js/lib/loaders/loader'>;
}
declare module 'pixi.js/lib/loaders/spritesheetParser.js' {
  declare module.exports: $Exports<'pixi.js/lib/loaders/spritesheetParser'>;
}
declare module 'pixi.js/lib/loaders/textureParser.js' {
  declare module.exports: $Exports<'pixi.js/lib/loaders/textureParser'>;
}
declare module 'pixi.js/lib/mesh/canvas/CanvasMeshRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/canvas/CanvasMeshRenderer'>;
}
declare module 'pixi.js/lib/mesh/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/index'>;
}
declare module 'pixi.js/lib/mesh/Mesh.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/Mesh'>;
}
declare module 'pixi.js/lib/mesh/NineSlicePlane.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/NineSlicePlane'>;
}
declare module 'pixi.js/lib/mesh/Plane.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/Plane'>;
}
declare module 'pixi.js/lib/mesh/Rope.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/Rope'>;
}
declare module 'pixi.js/lib/mesh/webgl/MeshRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/mesh/webgl/MeshRenderer'>;
}
declare module 'pixi.js/lib/particles/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/particles/index'>;
}
declare module 'pixi.js/lib/particles/ParticleContainer.js' {
  declare module.exports: $Exports<'pixi.js/lib/particles/ParticleContainer'>;
}
declare module 'pixi.js/lib/particles/webgl/ParticleBuffer.js' {
  declare module.exports: $Exports<'pixi.js/lib/particles/webgl/ParticleBuffer'>;
}
declare module 'pixi.js/lib/particles/webgl/ParticleRenderer.js' {
  declare module.exports: $Exports<'pixi.js/lib/particles/webgl/ParticleRenderer'>;
}
declare module 'pixi.js/lib/particles/webgl/ParticleShader.js' {
  declare module.exports: $Exports<'pixi.js/lib/particles/webgl/ParticleShader'>;
}
declare module 'pixi.js/lib/polyfill/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/polyfill/index'>;
}
declare module 'pixi.js/lib/polyfill/Math.sign.js' {
  declare module.exports: $Exports<'pixi.js/lib/polyfill/Math.sign'>;
}
declare module 'pixi.js/lib/polyfill/Object.assign.js' {
  declare module.exports: $Exports<'pixi.js/lib/polyfill/Object.assign'>;
}
declare module 'pixi.js/lib/polyfill/requestAnimationFrame.js' {
  declare module.exports: $Exports<'pixi.js/lib/polyfill/requestAnimationFrame'>;
}
declare module 'pixi.js/lib/prepare/BasePrepare.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/BasePrepare'>;
}
declare module 'pixi.js/lib/prepare/canvas/CanvasPrepare.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/canvas/CanvasPrepare'>;
}
declare module 'pixi.js/lib/prepare/index.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/index'>;
}
declare module 'pixi.js/lib/prepare/limiters/CountLimiter.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/limiters/CountLimiter'>;
}
declare module 'pixi.js/lib/prepare/limiters/TimeLimiter.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/limiters/TimeLimiter'>;
}
declare module 'pixi.js/lib/prepare/webgl/WebGLPrepare.js' {
  declare module.exports: $Exports<'pixi.js/lib/prepare/webgl/WebGLPrepare'>;
}
