/**
 * @author Luciano Graziani @lgraziani2712
 * @license {@link http://www.opensource.org/licenses/mit-license.php|MIT License}
 *
 * @flow
 */

export const ACTION_CONTAINER_TITLE = 'PONÉ ACÁ LAS PIEZAS';
export const ACTION_CONTAINER_TOOLTIP =
  'ES EL BLOQUE PRINCIPAL. ACÁ ES DONDE SE DEBEN PONER TODAS LAS PIEZAS.';

export const MOVE_LEFT_TITLE = 'MOVER A LA IZQUIERDA';
export const MOVE_LEFT_TOOLTIP = 'MUEVE UN PASO A LA IZQUIERDA';
export const MOVE_RIGHT_TITLE = 'MOVER A LA DERECHA';
export const MOVE_RIGHT_TOOLTIP = 'MUEVE UN PASO A LA DERECHA';
export const MOVE_FORWARD_TITLE = 'MOVER HACIA ARRIBA';
export const MOVE_FORWARD_TOOLTIP = 'MUEVE UN PASO ADELANTE';
export const MOVE_BACKWARD_TITLE = 'MOVER HACIA ABAJO';
export const MOVE_BACKWARD_TOOLTIP = 'MUEVE UN PASO ATRÁS';

export const SIMPLE_LOOP_TITLE_1 = 'REPETIR';
export const SIMPLE_LOOP_TITLE_2 = 'VECES';
export const SIMPLE_LOOP_TOOLTIP =
  'REPITE UNA CIERTA CANTIDAD DE VECES LOS BLOQUES QUE ESTÉN ADENTRO';

export const REPEAT_X_TITLE = SIMPLE_LOOP_TITLE_2;
export const REPEAT_X_TOOLTIP = 'REPITE EL MISMO BLOQUE UNA CIERTA CANTIDAD DE VECES';
